  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: mfa-keycloak
    depends_on:
      - postgres
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
    networks:
      - internal
